api_version = "2026-01"

[[extensions]]
name = "t:name"
handle = "cis-pickup-customization"
type = "function"
uid = "976b4e98-a5c6-7e16-c839-1100106b5618775dbecd"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.delivery-options.transform.run"
  input_query = "src/cart_delivery_options_transform_run.graphql"
  export = "cart-delivery-options-transform-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/app/pickup-customization"
  details = "/app/pickup-customization/[id]"
